ServerEvents.recipes(event => {
	event.remove({ output: 'createaddition:electrum_wire'})
	event.remove({ output: 'createaddition:copper_spool'})
	event.remove({ output: 'createaddition:gold_spool'})
	event.remove({ output: 'createaddition:electrun_ingot'})
	event.remove({ output: 'createaddition:electrun_sheet'})
	event.remove({ output: 'createaddition:large_connector'})
	event.remove({ output: 'createaddition:connector'})
	event.remove({ output: 'createaddition:festive_spool'})
	event.remove({ output: 'createaddition:spool'})
	event.remove({ output: 'createaddition:electric_motor'})
	event.remove({ output: 'createaddition:alternator'})
	event.remove({ output: 'createaddition:creative_energy'})
	event.remove({ output: 'createaddition:redstone_relay'})
	event.remove({ output: 'createaddition:modular_accumulator'})
	event.remove({ output: 'createaddition:tesla_coil'})
	event.remove({ output: 'createaddition:portable_energy_interface'})
	event.remove({ output: 'createaddition:capacitor'})
	event.remove({ output: 'createaddition:zinc_sheet'})
	event.remove({ output: 'createaddition:electrum_rod'})
	event.remove({ output: 'createaddition:gold_wire'})
	event.remove({ output: 'createaddition:copper_wire'})
})

	
